apiVersion: apps/v1
kind: Deployment
metadata:
  name: dosy1.0
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dosy1.0
  template:
    metadata:
      labels:
        app: dosy1.0
    spec:
      containers:
        - name: dosy1.0
          image: dosy1.0:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: dosy1.0-balancer
spec:
  selector:
    app: dosy1.0
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
